# Cudaserver

EXE 			= run_transposer_app
LOCAL_INCLUDE	= ./include
LOCAL_SRC		= ./src
LOCAL_BUILD 	= build

# $@ is the target (eg: main.o)
# $< is the source (eg: main.cu)

$(EXE): $(LOCAL_BUILD)/main.o
	nvcc -lcusparse -o $(EXE) $(LOCAL_BUILD)/main.o

$(LOCAL_BUILD)/main.o: $(LOCAL_SRC)/main.cu
	nvcc -lcusparse -I$(LOCAL_INCLUDE) -c $< -o $@

# The .PHONY rule keeps make from doing something with a file named clean.
.PHONY: clean test

clean:
	rm -f $(EXE) $(LOCAL_BUILD)/main.o

test:
	@echo "Starting test application...\n\n"
	@./$(EXE)