# Macchina locale Incud

EXE 			= run_transposer_app
LOCAL_INCLUDE	= ./include
LOCAL_SRC		= ./src
LOCAL_BUILD 	= build
GENCODE_FLAGS   = -m64 -gencode arch=compute_30,code=sm_30 -lcudart -lcusparse -lcublas

# $@ is the target (eg: main.o)
# $< is the source (eg: main.cu)

$(EXE): $(LOCAL_BUILD)/main.o
	nvcc -ccbin g++-6 $(GENCODE_FLAGS) -o $(EXE) $(LOCAL_BUILD)/main.o

$(LOCAL_BUILD)/main.o: $(LOCAL_SRC)/main.cu
	nvcc -ccbin g++-6 $(GENCODE_FLAGS) -I$(LOCAL_INCLUDE) -c $< -o $@


# The .PHONY rule keeps make from doing something with a file named clean.
.PHONY: clean test

clean:
	rm -f $(EXE) $(LOCAL_BUILD)/main.o

test:
	@echo "Starting test application...\n\n"
	@./$(EXE)